/* Shared Tailwind CDN config — must be loaded AFTER the Tailwind CDN script
   so the `tailwind` global exists. The CDN re-scans the DOM when .config is
   assigned, applying our custom colors (coral, brand-purple, etc). */
tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#fbf8ff',
        surface: '#fbf8ff',
        'surface-cream': '#fdf7ff',
        'surface-bright': '#fbf8ff',
        'surface-container': '#eeecf8',
        'surface-container-low': '#f4f2fe',
        'surface-container-high': '#e9e7f2',
        'surface-container-highest': '#e3e1ed',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e3e1ed',
        'surface-dim': '#dad9e4',
        'on-surface': '#1a1b23',
        'on-surface-variant': '#454654',
        'on-background': '#1a1b23',
        outline: '#757686',
        'outline-variant': '#c5c5d7',
        'inverse-surface': '#2f3038',
        'inverse-on-surface': '#f1effb',

        primary: '#5B6EF5',
        'primary-container': '#5366ed',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bcc2ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#000c61',
        'on-primary-fixed-variant': '#1c32be',
        'inverse-primary': '#bcc2ff',
        'surface-tint': '#3b4ed6',

        secondary: '#ab3500',
        'secondary-container': '#fe6a34',
        'secondary-fixed': '#ffdbd0',
        'secondary-fixed-dim': '#ffb59d',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5d1900',
        'on-secondary-fixed': '#390c00',
        'on-secondary-fixed-variant': '#832600',

        tertiary: '#914800',
        'tertiary-container': '#b65c00',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb784',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',

        error: '#ba1a1a',
        'error-red': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        'neutral-black': '#1A1A1A',
        coral: '#FF6B35',
        'brand-purple': '#8069BF',
        'accent-yellow': '#ffdf93',
        'accent-rose': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-xl': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'label-bold': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'display-xl': ['120px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '900' }],
        'headline-xl': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-xl-mobile': ['48px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.0', fontWeight: '700' }],
      },
    },
  },
};
